### PR TITLE
Add lemon graph classes

### PR DESCRIPTION
**Pull request by OrkoHunter**
This PR adds all the files inside `lemon/concepts` directory. These are the basic definition of graph classes.

### CODE REVIEW

**Comment by ysitu** [comment]
Why are not LEMON source files all in one PR?

**Comment by OrkoHunter** [comment]
I thought that we need to look at the `lemon/concepts` and `lemon/bits` separately. Sending the stuff with #2 was making it too large for GitHub to actually show the code.

**Comment by ysitu** [comment]
Frankly speaking, a 40,000-line source import is not reviewable. I can only trust you that you are doing the right thing, which will need to be verified by building and running LEMON's tests.

**Comment by OrkoHunter** [comment]
Okay then, I'll make that all in one PR.

**Pull request closed without merging**
