### PR TITLE
Add LEMON source files

### PR DESCRIPTION
**Pull request by OrkoHunter**
This PR adds the LEMON source files excluding `lemon/concepts` and `lemon/bits`.

There are possibly many more modifications to be done for the library to build. We can enlist them over here https://github.com/networkx/networkx-lemon/wiki/Changes-for-successful-build and then finally publish all the changes with some file similar to `NOTICE`.

### CODE REVIEW

**Comment by ysitu** [comment]
Why does `math.h` conflict with `cmath`?

**Comment by OrkoHunter** [comment]
The cmath header file is also named `math.h`. Even if we rename the lemon file `Math.h`, it won't work.

**Comment by ysitu** [comment]
Have you verified that it does indeed cause builds to break? It seems very improbable to me that `#include <cmath>` would somehow find `lemon/math.h`.

**Comment by OrkoHunter** [comment]
Well, I didn't try it with `#include<cmath>` but it did break with `#include "math.h"> which was already there in the source code.

**Comment by ysitu** [comment]
`#include "math.h"` is bad practice, two-fold. First, in C++, you should always use `#include <cmath>`. Second, you should not have a header file of your name with exactly the same name as a system header file.

**Comment by OrkoHunter** [comment]
Okay, let me verify it with `<cmath>`.

**Comment by OrkoHunter** [comment]
I think I did not convey the matter properly.

The `math.h` file present inside `src/lemon/` contains some extensions to the `cmath` library and it _does_ contain the line `#include<cmath>`. Now the files enlisted in https://github.com/networkx/networkx-lemon/wiki/Changes-for-successful-build need to import the `math.h` file present inside the `src/lemon/` directory. But they have the line `#include "math.h"` which does not include the customized `math.h` of LEMON but includes the C `math.h` library. That's why I had to change the name of the file `math.h` to something not conflicting. It's also a bad practice to have a file which has exactly same name as of a built-in library.

**Comment by ysitu** [comment]
Hmm... Shouldn't they use `#include <lemon/math.h>` instead? I thought that they would `#include <lemon/xxx.h>` consistently.

**Comment by OrkoHunter** [comment]
I wonder how things have been working for them with such faulty practice.

**Comment by ysitu** [comment]
Technically speaking, that should work. The compiler should search the system include directories first for `<math.h>` and your own source directories first for `"math.h"`. The caveat is that you need to set the compiler flags correctly.

**Comment by OrkoHunter** [comment]
> .. you need to set the compiler flags correctly.

Yes, ofcourse. But I think we do not have much with `python setup.py build`.

**Comment by OrkoHunter** [comment]
I have added all the LEMON source files in this PR. Also, I have added a commit about the change in the source.

**Comment by OrkoHunter** [comment]
I have pushed a branch over my fork https://github.com/orkohunter/networkx-lemon/tree/math-header with the commit related to math.h _reverted_ and have added a `setup.py`. You can run `python setup.py build_clib` without any more changes over the branch.

Most of the errors in the build are similar to the `::xyz function has not been declared`. This may suggest that the actual `lemon/math.h` has not been included but instead the c header `math.h` got included. And this all gets fixed with changing the name of the file.

Technically speaking, using `#include "lemon/math.h"` should be sufficient because of specifying the location and using double quotes which tells the compiler to look into the local directory first. But I can't come up with a good reason for this behavior except for blaming the conflict between the system and local file names.

**Pull request merged**
