### PR TITLE
[WIP] Wrap LEMON Digraph class

### PR DESCRIPTION
**Pull request by OrkoHunter**

### CODE REVIEW

**Comment by OrkoHunter** [comment]
This can be worked out after #14 goes in.

**Comment by OrkoHunter** [comment]
I'm not really sure whether we need this class or not. There's this [`ListDigraph`](https://github.com/networkx/networkx-lemon/blob/master/src/lemon/list_graph.h) (Edit: which is also the default for shortest path algorithms) which seems to be an extension to the LEMON `Digraph` class which is, as written  [in the doc](http://lemon.cs.elte.hu/pub/doc/1.2.3/a00203.html), more faster implementation than the original class. And I can't see a clear dependency of both on each other.

**Comment by ysitu** [comment]
Use `StaticDigraph`.

**Comment by OrkoHunter** [comment]
We may reopen this when we'd need `Digraph`.

**Pull request closed without merging**
