### PR TITLE
Set up appveyor-ci

### PR DESCRIPTION
**Pull request by OrkoHunter**
We have done rewriting of things because of windows support at later stage. Lets keep it early.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
@chebee7i Can you please set AppVeyor for networkx-lemon?

**Comment by OrkoHunter** [comment]
@chebee7i Ping.

**Comment by chebee7i** [comment]
Done.

**Comment by OrkoHunter** [comment]
Great! Thanks.

**Pull request merged**
